/* Fichas oficiais das equipes — extraidas de formula1.com/en/teams/{slug} em 20/07/2026.
   O site oficial bloqueia leitura pelo navegador (CORS), por isso o snapshot local.
   Chave = slug oficial; "asset" = pasta usada no CDN de imagens 2026. */
window.F1_TEAMS = {
 "ferrari": {
  "asset": "ferrari",
  "full": "Scuderia Ferrari HP",
  "base": "Maranello, Italy",
  "chief": "Frédéric Vasseur",
  "tech": "Loic Serra / Enrico Gualtieri",
  "chassis": "SF-26",
  "engine": "Ferrari",
  "reserve": "Antonio Giovinazzi",
  "since": "1950",
  "titles": "16",
  "gpsAll": "1133",
  "podiumsAll": "647",
  "polesAll": "254",
  "sPos": "2nd",
  "sPts": "285",
  "sWins": "2",
  "sPodiums": "9",
  "sPoles": "0",
  "sTop10": "18",
  "sFastest": "1",
  "sDnf": "2"
 },
 "red-bull-racing": {
  "asset": "redbullracing",
  "full": "Oracle Red Bull Racing",
  "base": "Milton Keynes, United Kingdom",
  "chief": "Laurent Mekies",
  "tech": "Pierre Waché",
  "chassis": "RB22",
  "engine": "Red Bull Ford",
  "since": "1997",
  "titles": "6",
  "gpsAll": "428",
  "podiumsAll": "236",
  "polesAll": "111",
  "sPos": "4th",
  "sPts": "151",
  "sWins": "0",
  "sPodiums": "3",
  "sPoles": "0",
  "sTop10": "14",
  "sFastest": "1",
  "sDnf": "5"
 },
 "mclaren": {
  "asset": "mclaren",
  "full": "McLaren Mastercard F1 Team",
  "base": "Woking, United Kingdom",
  "chief": "Andrea Stella",
  "tech": "Peter Prodromou / Neil Houldey",
  "chassis": "MCL40",
  "engine": "Mercedes",
  "reserve": "Leonardo Fornaroli, Pato O’Ward",
  "since": "1966",
  "titles": "10",
  "gpsAll": "1004",
  "podiumsAll": "448",
  "polesAll": "177",
  "sPos": "3rd",
  "sPts": "195",
  "sWins": "0",
  "sPodiums": "4",
  "sPoles": "0",
  "sTop10": "13",
  "sFastest": "2",
  "sDnf": "2"
 },
 "mercedes": {
  "asset": "mercedes",
  "full": "Mercedes-AMG PETRONAS Formula One Team",
  "base": "Brackley, United Kingdom",
  "chief": "Toto Wolff",
  "tech": "James Allison",
  "chassis": "W17",
  "engine": "Mercedes",
  "reserve": "Fred Vesti",
  "since": "1970",
  "titles": "8",
  "gpsAll": "339",
  "podiumsAll": "211",
  "polesAll": "146",
  "sPos": "1st",
  "sPts": "358",
  "sWins": "8",
  "sPodiums": "13",
  "sPoles": "10",
  "sTop10": "15",
  "sFastest": "0",
  "sDnf": "3"
 },
 "aston-martin": {
  "asset": "astonmartin",
  "full": "Aston Martin Aramco Formula One Team",
  "base": "Silverstone, United Kingdom",
  "chief": "Adrian Newey",
  "tech": "Enrico Cardile",
  "chassis": "AMR26",
  "engine": "Honda",
  "reserve": "Jak Crawford",
  "since": "2018",
  "titles": "0",
  "gpsAll": "162",
  "podiumsAll": "12",
  "polesAll": "1",
  "sPos": "10th",
  "sPts": "1",
  "sWins": "0",
  "sPodiums": "0",
  "sPoles": "0",
  "sTop10": "1",
  "sFastest": "0",
  "sDnf": "10"
 },
 "alpine": {
  "asset": "alpine",
  "full": "BWT Alpine Formula One Team",
  "base": "Enstone, United Kingdom",
  "chief": "Flavio Briatore (Executive Advisor), Steve Nielsen (Managing Director)",
  "tech": "David Sanchez",
  "chassis": "A526",
  "engine": "Mercedes",
  "reserve": "Paul Aron, Kush Maini",
  "since": "1986",
  "titles": "2",
  "gpsAll": "402",
  "podiumsAll": "61",
  "polesAll": "20",
  "sPos": "5th",
  "sPts": "61",
  "sWins": "0",
  "sPodiums": "1",
  "sPoles": "0",
  "sTop10": "13",
  "sFastest": "0",
  "sDnf": "1"
 },
 "williams": {
  "asset": "williams",
  "full": "Atlassian Williams F1 Team",
  "base": "Grove, United Kingdom",
  "chief": "James Vowles",
  "tech": "Pat Fry",
  "chassis": "FW48",
  "engine": "Mercedes",
  "since": "1978",
  "titles": "8",
  "gpsAll": "861",
  "podiumsAll": "245",
  "polesAll": "128",
  "sPos": "8th",
  "sPts": "11",
  "sWins": "0",
  "sPodiums": "0",
  "sPoles": "0",
  "sTop10": "5",
  "sFastest": "0",
  "sDnf": "4"
 },
 "haas": {
  "asset": "haas",
  "full": "TGR Haas F1 Team",
  "base": "Kannapolis, United States",
  "chief": "Ayao Komatsu",
  "tech": "Andrea De Zordo",
  "chassis": "VF-26",
  "engine": "Ferrari",
  "reserve": "Jack Doohan, Ryo Hirakawa",
  "since": "2016",
  "titles": "0",
  "gpsAll": "224",
  "podiumsAll": "0",
  "polesAll": "0",
  "sPos": "7th",
  "sPts": "21",
  "sWins": "0",
  "sPodiums": "0",
  "sPoles": "0",
  "sTop10": "5",
  "sFastest": "0",
  "sDnf": "3"
 },
 "racing-bulls": {
  "asset": "racingbulls",
  "full": "Visa Cash App Racing Bulls Formula One Team",
  "base": "Faenza, Italy",
  "chief": "Alan Permane",
  "tech": "Tim Goss",
  "chassis": "VCARB 03",
  "engine": "Red Bull Ford",
  "reserve": "Yuki Tsunoda",
  "since": "1985",
  "titles": "0",
  "gpsAll": "409",
  "podiumsAll": "6",
  "polesAll": "1",
  "sPos": "6th",
  "sPts": "61",
  "sWins": "0",
  "sPodiums": "0",
  "sPoles": "0",
  "sTop10": "13",
  "sFastest": "0",
  "sDnf": "1"
 },
 "audi": {
  "asset": "audi",
  "full": "Audi Revolut F1 Team",
  "base": "Hinwil, Switzerland",
  "chief": "Mattia Binotto",
  "tech": "James Key",
  "chassis": "R26",
  "engine": "Audi",
  "since": "2026",
  "titles": "0",
  "gpsAll": "10",
  "podiumsAll": "0",
  "polesAll": "0",
  "sPos": "9th",
  "sPts": "10",
  "sWins": "0",
  "sPodiums": "0",
  "sPoles": "0",
  "sTop10": "3",
  "sFastest": "0",
  "sDnf": "3"
 },
 "cadillac": {
  "asset": "cadillac",
  "full": "Cadillac Formula 1 Team",
  "base": "Silverstone, United Kingdom",
  "chief": "Graeme Lowdon",
  "tech": "Nick Chester",
  "chassis": "MAC-26",
  "engine": "Ferrari",
  "reserve": "Zhou Guanyu",
  "since": "2026",
  "titles": "0",
  "gpsAll": "10",
  "podiumsAll": "0",
  "polesAll": "0",
  "sPos": "11th",
  "sPts": "0",
  "sWins": "0",
  "sPodiums": "0",
  "sPoles": "0",
  "sTop10": "0",
  "sFastest": "0",
  "sDnf": "7"
 }
};
